version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t nookthana70/react-form:latest .
      - run:
          name: ตรวจสอบ Docker images
          command: docker images
      - run:
          name: ตรวจสอบ Docker containers
          command: docker ps -a
      - run:
          name: Tag Docker image
          command: |
            docker tag nookthana70/react-form:latest nookthana70/react-form:${CIRCLE_SHA1}
      - run:
          name: Push Docker image
          command: |
            docker push nookthana70/react-form:latest
            docker push nookthana70/react-form:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
