version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t nookthana70/react-form:latest .
      - run:
          name: Tag Docker image
          command: |
            docker tag nookthana70/react-form:latest nookthana70/react-form:${CIRCLE_SHA1}
      - run:
          name: Push Docker image
          command: |
            docker push nookthana70/react-form:latest
            docker push nookthana70/react-form:${CIRCLE_SHA1}
        